#ifndef CAUDIO_VERSION_H
#define CAUDIO_VERSION_H

#define CAUDIO_VERSION_MAJOR 0
#define CAUDIO_VERSION_MINOR 0
#define CAUDIO_VERSION_PATCH 1
#define CAUDIO_VERSION_STRING "0.0.1"

#endif /* CAUDIO_VERSION_H */
